language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

git:
    depth: 1

php:
    - 7.2
    - 7.3

before_install:
    - composer require php-coveralls/php-coveralls --prefer-dist --no-interaction --no-progress
    - composer global require localheinz/composer-normalize --prefer-dist --no-interaction --no-progress

install:
    - mkdir -p build/logs
    - composer install --prefer-dist --no-interaction --no-progress

script:
    - composer normalize --indent-size 4 --indent-style space --dry-run
    # - ./vendor/bin/simple-phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
    # - travis_retry php vendor/bin/php-coveralls
